@extends ('home.layout')

@section ('content')
<style type="text/css">
	.question{
		background-color: #fcfcfc;
		border: 1px solid #f6f6f6;
		border-right: 0;
		border-bottom: 1px solid #f6f6f6;
		color: #888;
		display: block;
		letter-spacing: 0;
		outline: 0;
		padding: 0 10px;
		text-decoration: none;
		white-space: nowrap;
		overflow: hidden!important;
		text-overflow: ellipsis;
		padding: 10px;
		margin-top: 10px;
	}
	.answer{
		display: none;
		border: 1px solid #f6f6f6;
		padding: 20px;
		margin: -1px 0 20px;
		overflow: hidden;
		width: 100%;
		line-height: 19px;
		-webkit-box-shadow: 0 1px 1px 0 rgba(180,180,180,0.1);
		-moz-box-shadow: 0 1px 1px 0 rgba(180,180,180,0.1);
		box-shadow: 0 1px 1px 0 rgba(180,180,180,0.1);
	}
</style>
<div id="page-title">
        <div id="page-title-inner">
            <!-- start: Container -->

            <div class="container">
                <h2><i class="fa fa-building-o"></i>Frequently Asked Questions</h2>
            </div><!-- end: Container  -->
        </div>
    </div>

    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            <div class="media">
                <div class="media-body">
                    <div class="title"><h3>About Infermap</h3></div>

                    <div class="question" id="q1">
                        <strong>What is Infermap?</strong>
                    </div>

                    <div class="answer" id="q1a">
                        Infermap is a great way to find your dream career. We
                        have developed tools and services to help Indian
                        students make well-informed educational decisions and
                        manage transactions in an efficient and transparent
                        way. We make it easier for you to find a career by
                        offering:

                        <ul>
                            <li>A vast database of colleges and educational
                            institutes</li>

                            <li>Our Milestone Tracker to help you organise the
                            buying process</li>

                            <li>Smarter financial calculators, which are fully
                            integrated with our search tools</li>

                            <li>Access to the best Property Coaches to make
                            your homebuying journey easier</li>
                        </ul>
                    </div>
                    

                    <div class="question" id="q2">
                        <strong>What areas does Infermap cover?</strong>
                    </div>

                    <div class="answer" id="q2a">
                        We cover engineering colleges of the whole of the India
                        with our college listings, which are aimed to be most
                        transparent and satisfy your queries..
                    </div>
                    

                    <div class="question" id="q3">
                        <strong>Where do Infermap listings come from?</strong>
                    </div>

                    <div class="answer" id="q3a">
                        Our listings are generated by compiling content from
                        various authenticated government and college agencies.
                    </div>
                    

                    <div class="question" id="q4">
                        <strong>Does Infermap charge fees?</strong>
                    </div>

                    <div class="answer" id="q4a">
                        It is completely free to use our site and sign up to
                        Infermap.
                    </div>
                </div>
            </div>

            <div class="media">
                <div class="media-body">
                    <div class="title"><h3 >Using Infermap</h3></div>

                    <div class="question" id="q5">
                        <strong>Who can use Infermap?</strong>
                    </div>

                    <div class="answer" id="q5a">
                        Anyone can use Infermap. Whether you're looking for
                        colleges or extra educational help, Infermap is the
                        perfect place for you.
                    </div>
                    

                    <div class="question" id="q6">
                        <strong>What features do you provide?</strong>
                    </div>

                    <div class="answer" id="q6a">
                        <ul class="check_list">
                            <li>Our Path Finder, to guide you through the
                            entire process.</li>

                            <li>A wealth of smart calculators to help you
                            clearly understand your choices and make informed
                            decisions throughout your educational journey.</li>

                            <li>A predominantly map-based search experience, to
                            give you a better idea of where you’re
                            looking.</li>

                            <li>A panel of tools to help you every step of the
                            way.</li>
                        </ul>
                    </div>
                    

                    <div class="question" id="q7">
                        <strong>How do I create a Infermap account?</strong>
                    </div>

                    <div class="answer" id="q7a">
                        You can create an account at any point by clicking on
                        the Register button in our site header. From there you
                        just input your e-mail and and some other details.
                        Alternatively, you can sign in via Facebook or
                        Google.These Alternatives would be available soon
                    </div>
                    

                    <div class="question" id="q8">
                        <strong>Why should I create an account?</strong>
                    </div>

                    <div class="answer" id="q8a">
                        Creating a free account gives you access to the full
                        benefits of Infermap. This includes saving all your
                        information and favourite listings. We also ask you to
                        agree to our Terms of Service, Privacy Policy. In the
                        future we hope to bring you even more features, so it's
                        well worth signing up today.
                    </div>
                    

                    <div class="question" id="q9">
                        <strong>Why should I create an account?</strong>
                    </div>

                    <div class="answer" id="q9a">
                        Creating a free account gives you access to the full
                        benefits of Infermap. This includes saving all your
                        information and favourite listings. We also ask you to
                        agree to our Terms of Service, Privacy Policy. In the
                        future we hope to bring you even more features, so it's
                        well worth signing up today.
                    </div>
                    

                    <div class="question" id="q10">
                        <strong>How do I update my account settings or cancel
                        my account?</strong>
                    </div>

                    <div class="answer" id="q10a">
                        You can update your account settings and cancel your
                        account on your account page.
                    </div>
                    

                    <div class="question" id="q11">
                        <strong>I'm an educational institute. Can I use
                        Infermap?</strong>
                    </div>

                    <div class="answer" id="q11a">
                        Of Course. You can get in touch with your potential
                        students, just get on this journey with us.. Get
                        started by contacting us using our "Talk to us" tool.
                        We're working on features designed specifically for
                        you. Or just drop us a mail at data@infermap.com or infermap@gmail.com and
                        we'll get in touch with you.
                    </div>
                </div>
            </div>

            <div class="media">
                <div class="media-body">
                    <div class="title"><h3 >Security &amp; Privacy</h3></div>

                    <div class="question" id="q12">
                        <strong>What information does Infermap
                        collect?</strong>
                    </div>

                    <div class="answer" id="q12a">
                        We collect the information you choose to provide when
                        creating an account, along with information provided
                        for the calculators. This information includes your
                        name, e-mail address, phone number, and information you
                        provide in the application and associated
                        documents.<br>
                        We use cookies to enable our servers to recognise your
                        web browser, and help us understand how and when you
                        visit the site. For further information, please consult
                        our Privacy Policy.
                    </div>
                    

                    <div class="question" id="q13">
                        <strong>Does Infermap send my personal information to
                        anyone else?</strong>
                    </div>

                    <div class="answer" id="q13a" >
                        We may provide some aggregate, anonymous information to
                        our legal and mortgage partners about how often and in
                        what ways people use our site. We never provide
                        information that would identify you personally and we
                        never sell your information to third parties. For
                        further information, please consult our Privacy Policy.
                    </div>
                    

                    <div class="question" id="q14">
                        <strong>Is personal information about me
                        secure?</strong>
                    </div>

                    <div class="answer" id="q14a" >
                        We store all of our information, using
                        industry-standard SSL security techniques. As with any
                        online account, we suggest you select and protect your
                        password appropriately, and sign off after you have
                        finished accessing your account.<br>
                        For further information, please consult our Privacy
                        Policy.
                    </div>
                    

                    <div class="question" id="q15">
                        <strong>Where can I find more information on your
                        policies?</strong>
                    </div>

                    <div class="answer" id="q15a">
                        For further information, please consult our Terms of
                        Service and Privacy Policy.
                    </div>
                </div>
            </div>

            <div class="media">
                <div class="media-body">
                    <div class="title"><h3 >Contact</h3></div>

                    <div class="question" id="q16">
                        <strong>How do I contact Infermap?</strong>
                    </div>

                    <div class="answer" id="q16a">
                        You can contact us to provide feedback or ask any
                        questions via our Contact Page (Talk To us). For
                        general questions you can always e-mail us at
                        info@infermap.com.
                    </div>
                    

                    <div class="question" id="q17">
                        <strong>How do I find out about new features and tell
                        my friends?</strong>
                    </div>

                    <div class="answer" id="q17a">
                        Just sign up to Infermap and we will e-mail you new
                        features as soon as they are released. You can also
                        follow us on Twitter and like our Facebook page to stay
                        in touch.
                    </div>
                </div>
            </div>
        </div>
    </div>
<script type="text/javascript">

var lasttoggle = "doggy";

	$(".question").click(function(){
	  $("#"+this.id+"a").slideToggle();
	 
	});

</script>
@endsection